### ISSUE TITLE
Declarar la situación del problema

### ISSUE THREAD

**Issue by JuanPabloSalazarVasquez** [JuanPabloSalazarVasquez/equipo6_gaa_ppi2020#3]

**Comment by JuanPabloSalazarVasquez** [comment]
"A los estudiantes se nos dificulta el desarrollo de las asignaciones por la falta de orden, ya que son bastantes y cada una tiene una fecha limite diferente. Esto provoca que ocasionalmente olvidemos realizar o incluso entregar algún trabajo."

**Comment by JuanPabloSalazarVasquez** [comment]
Entrada en la Wiki disponible.

**Comment by marthaduque** [comment]
se debe asignar responsables
