### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by JuanPabloSalazarVasquez** [JuanPabloSalazarVasquez/equipo6_gaa_ppi2020#6]

**Comment by JuanPabloSalazarVasquez** [comment]
"El nuevo sistema tendrá la opción de organizar los proyectos, trabajos o tareas de forma explícita para así ayudar a realizar todo con tiempo, dando avisos al acercarse la fecha de entrega, y dando la opción de agregarle la nota asignada posteriormente."

**Comment by JuanPabloSalazarVasquez** [comment]
Entrada en la Wiki disponible.

**Comment by marthaduque** [comment]
se debe asignar responsables
